/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SocialNetworkAccountRelationListing {
  DataService?: DWDataService;
}
export interface DWDataService {
  socialnetworkid?: number;
  socialnetworkaccountname?: string;
  status?: number;
  effectivedate?: string;
  terminateddate?: string;
  userid?: number;
  user_code?: string;
  user_name?: string;
  user_email?: string;
  socialnetworkname?: string;
  socialnetworkaccountno?: string;
}
