/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataService {
  DataService?: DWDataService;
}
export interface DWDataService {
  user_id?: number;
  prg_id?: number;
  user_code?: string;
  user_name?: string;
  user_password?: string;
  user_level?: string;
  orgn_id?: number;
  user_email?: string;
}
