/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataService {
  DataService?: DWDataService;
}
export interface DWDataService {
  orgn_id?: number;
  orgn_short_name?: string;
  orgn_code?: string;
  orgn_type?: string;
  orgn_full_name?: string;
  orgn_address1?: string;
  orgn_address2?: string;
  orgn_address3?: string;
  orgn_faxno?: string;
  orgn_postcode?: string;
  orgn_phone?: string;
  orgn_contact_person?: string;
  orgn_mailing_add_id?: number;
  site_id?: number;
}
