/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrganisationProfileListing {
  DataService?: DWDataService;
}
export interface DWDataService {
  prof_id?: number;
  class_shortname?: string;
  is_lowest?: string;
  class_desc?: string;
  class_code?: string;
}
