/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "FisMessageTypeAll".
 */
export type FisMessageTypeAll = MessageType & FisMessageType;
/**
 * List of FIS commands, extended from Command.
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "FisCommandEnum".
 */
export type FisCommandEnum = Command | FisCommand;
/**
 * List of FIS query, extended from Query.
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "FisQueryEnum".
 */
export type FisQueryEnum = Query | FisQuery;

export interface Testenumschema {
  [k: string]: unknown;
}

/**
 * Message type. To identify different types of message.
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "MessageType".
 */
export enum MessageType {
  Base = "Base",
  Command = "Command",
  MicroserviceNotification = "MicroserviceNotification",
  Notification = "Notification",
  Query = "Query",
  Request = "Request",
  Response = "Response",
  ResponseData = "ResponseData",
  ResponseException = "ResponseException",
  ResponseStatus = "ResponseStatus",
  ResponseSubscription = "ResponseSubscription",
  Subscription = "Subscription"
}
/**
 * List of commands
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "CommandEnum".
 */
export enum Command {
  New = "New",
  Update = "Update",
  Delete = "Delete",
  SetFieldValue = "SetFieldValue",
  Save = "Save",
  Cancel = "Cancel",
  Commit = "Commit"
}
/**
 * Query request.
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "QueryEnum".
 */
export enum Query {
  General = "General"
}
/**
 * Request to subscribe messages
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "SubscriptionEnum".
 */
export enum Subscription {
  General = "General"
}
/**
 * FisMessage type. To identify different types of message.
 *
 * This interface was referenced by `Testenumschema`'s JSON-Schema
 * via the `definition` "FisMessageType".
 */
export enum FisMessageType {
  FisBase = "FisBase",
  FisCommand = "FisCommand",
  FisQuery = "FisQuery",
  FisRequest = "FisRequest",
  FisResponse = "FisResponse"
}
export enum FisCommand {
  Retrieve = "Retrieve",
  Modify = "Modify",
  SetColumn = "SetColumn"
}
export enum FisQuery {
  Retrieve = "Retrieve"
}
