/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EmployeeLeaveTypeListing {
  DataService?: DWDataService;
}
export interface DWDataService {
  emp_role_id?: number;
  emp_leave_mas_id?: number;
  ps_emp_leave_master_emp_lv_pro_rate?: string;
  ps_emp_leave_master_emp_lv_mas_create_ty?: string;
  ps_leave_desc?: string;
  emp_lv_mas_year?: number;
  emp_lv_mas_carr_forw?: number;
  emp_lv_mas_max_time?: number;
  emp_lv_pro_rate?: string;
  emp_lv_taken?: number;
  emp_lv_mas_earned?: number;
  emp_lv_mas_entitled?: number;
  emp_lv_mas_brou_forw?: number;
  ps_emp_leave_master_emp_lv_mas_open?: string;
  ps_emp_leave_master_emp_lv_mas_allow_car?: string;
  emp_lv_balance?: number;
}
